openapi: 3.1.0
info:
  title: Admin Content API
  version: 1.0.0
  description: API for managing uploads of quotes and images.
  contact:
    name: Soorya Akilesh
    email: soorya@abovecloud9.ai

servers:
  - url: /v1/admin/content

paths:
  /quotes/import:
    post:
      summary: Upload multiple quotes
      description: Allows uploading multiple quotes in a single request, with data provided as an Excel file or Google Sheets link.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                metadataLink:
                  type: string
                  description: A link to a Google Sheet containing data for the quotes.
      responses:
        '200':
          description: Quotes uploaded successfully.
        '400':
          description: Invalid input request. Possible issues include missing required fields, incorrect file format, or invalid Google Sheets link.
        '422':
          description: Validation error. The file or link contains invalid or incomplete data
        '500':
          description: Internal server error.

  /quotes:
    post:
      summary: Upload a single quote
      description: Allows uploading a single quote.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: Unique identifier for the quote.
                text:
                  type: string
                  description: Text of the quote.
                tags:
                  type: array
                  description: Tags associated with the quote.
                  items:
                    type: string
                lang:
                  type: string
                  description: Language code of the quote (e.g., en-US, es-ES).
              required:
                - id
                - text
                - lang
      responses:
        '200':
          description: Quote uploaded successfully.
        '400':
          description: Invalid input. Possible issues include missing required fields or invalid data format.
        '422':
          description: Validation error. The provided data does not meet expected criteria.
        '500':
          description: Internal server error. 

  /images/import:
  post:
    summary: Upload a folder of images
    description: Allows uploading a folder containing multiple images.
    requestBody:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              folder:
                type: string
                format: binary
                description: The folder containing the images to upload.
    responses:
      '200':
        description: Folder uploaded successfully.
      '400':
        description: Invalid input or malformed request.


 /images:
  post:
    summary: Upload a single image
    description: Allows uploading a single image file.
    requestBody:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              image:
                type: string
                format: binary
                description: The image file to upload.
    responses:
      '200':
        description: Image uploaded successfully.
      '400':
        description: Invalid input or malformed request.
      '500':
          description: Internal server error. 
